name: finalproject
description: A new Flutter project for DemoTrader App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5+1
  go_router: ^14.8.1
  shared_preferences: ^2.1.1
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  fl_chart: ^0.63.0
  image_picker: ^0.8.9
  path_provider: ^2.0.15
  collection: ^1.18.0

  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_auth_web: ^5.14.1
  cloud_firestore: ^5.6.5

  google_sign_in: ^6.1.0
  visibility_detector: ^0.4.0+2
  shimmer_animation: ^2.1.0
  animate_gradient: ^0.0.3
  model_viewer_plus: ^1.9.3
  candlesticks: ^2.1.0
  http: ^1.1.0
  intl: ^0.18.1
  url_launcher: ^6.1.10
  csv: ^5.0.0

dependency_overrides:
  js: ^0.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/logo_.png
    - lib/assets/images/cyborg_hand_left.png
    - lib/assets/images/cyborg_hand_right.png
    - lib/assets/images/google_logo.png
    - lib/assets/images/stock_market_basics.png
    - lib/assets/images/trading_fundamentals.png
    - lib/assets/images/market_analysis.png
    - lib/assets/images/risk_management.png
    - lib/assets/images/getting_started.png
    - lib/assets/images/useful_resources.png
