// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAU1Gq4qJOLonV8OjWYA9EC5tupb9lq10',
    appId: '1:967617334311:web:afe268ef6b5228bafe5202',
    messagingSenderId: '967617334311',
    projectId: 'demotraderapp',
    authDomain: 'demotraderapp.firebaseapp.com',
    storageBucket: 'demotraderapp.firebasestorage.app',
    measurementId: 'G-NKDBEB93GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeOaCcnGvvhNJdaQ3_KG6Ql5YhhaXMdfE',
    appId: '1:967617334311:android:093cccec46e7dbd0fe5202',
    messagingSenderId: '967617334311',
    projectId: 'demotraderapp',
    storageBucket: 'demotraderapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0cqR49efQ1X6s9gVjHw7PkyF_bWwnlEk',
    appId: '1:967617334311:ios:eefef8fa5bd5a627fe5202',
    messagingSenderId: '967617334311',
    projectId: 'demotraderapp',
    storageBucket: 'demotraderapp.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0cqR49efQ1X6s9gVjHw7PkyF_bWwnlEk',
    appId: '1:967617334311:ios:eefef8fa5bd5a627fe5202',
    messagingSenderId: '967617334311',
    projectId: 'demotraderapp',
    storageBucket: 'demotraderapp.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAU1Gq4qJOLonV8OjWYA9EC5tupb9lq10',
    appId: '1:967617334311:web:d2db40988e9e71f4fe5202',
    messagingSenderId: '967617334311',
    projectId: 'demotraderapp',
    authDomain: 'demotraderapp.firebaseapp.com',
    storageBucket: 'demotraderapp.firebasestorage.app',
    measurementId: 'G-K4MS1CMYK4',
  );
}
